AdminView/urls.py
from django.urls import path


from . import views

app_name = 'AdminView'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:labslot_id>/', views.detail, name='detail'),
]

WebApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('AdminView/', include('AdminView.urls')),
    path('admin/', admin.site.urls),
]

AdminView/models.py
from django.db import models


# Create your models here.
class LabSlot(models.Model):
    lab_time = models.TimeField('Time Chosen')
    lab_name = models.CharField(max_length=20)

    def __str__(self):
        return self.lab_name + " @ " + self.lab_time.strftime('%H:%M:%S')


class LabDemos(models.Model):
    lab = models.ForeignKey(LabSlot, on_delete=models.CASCADE)
    chosen_demos = models.CharField(max_length=200)

AdminView/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from django.template import loader
# Create your views here.
from .models import LabSlot


def index(request):
    lab_list = LabSlot.objects.order_by('-lab_name')[:5]
    template = loader.get_template('AdminView/index.html')
    context = {
        'lab_list': lab_list,
    }
    return HttpResponse(template.render(context, request))


def detail(request, labslot_id):
    lab = get_object_or_404(LabSlot, pk=labslot_id)
    return render(request, 'AdminView/detail.html', {'lab': lab})

AdminView/templates/AdminView/detail.html
<h1>{{ lab.lab_name }}</h1>
<p>At {{ lab.lab_time }}</p>

AdminView/templates/AdminView/index.html
{%  if lab_list %}
    <ul>
    {% for lab in lab_list %}
        <li>
            <a href="{%  url 'AdminView:detail' lab.id %}">{{ lab.lab_name }}</a>
        </li>
    {% endfor %}
    </ul>
    {% else %}
        <p>No labs available</p>
{%  endif %}